version: "3"
services:
  webserver:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../app:/app
      - ../src:/app/src

  app:
    build: services/php
    volumes:
      - ../app:/app
      - ../src:/app/src
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cv_db"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cv_db"
    ports:
      - "8080:80"

volumes:
  mysqldata: {}
