<?php

return [
    'db' => [
        'db_host' => 'db',
        'db_name' => 'cv_db',
        'db_user' => 'root',
        'db_pass' => 'root',
        'db_port' => '3306'
    ],
    'default_page' => 'home',
    'views' => [
        'home' => [
            'file' => 'home.php',
            'urlPath' => ['/', '/home'],
            'path' => '/../app/views/home.php',
            'route' => '/../views/layout.php',
            'title' => 'Accueil',
            'method' => ['GET', 'POST'],
            'protected' => false,
        ],
        'login' => [
            'file' => 'login.php',
            'urlPath' => ['/login', '/connexion'],
            'path' => '/../app/views/login.php',
            'route' => '/../views/layout.php',
            'title' => 'Connexion',
            'method' => ['GET', 'POST'],
            'protected' => false, // Il faut être connecté pour accéder à la page
        ],
        'register' => [
            'file' => 'signup.php',
            'urlPath' => ['/signup', '/inscription'],
            'path' => '/../app/views/signup.php',
            'route' => '/../views/layout.php',
            'title' => 'Inscription',
            'method' => ['GET', 'POST'],
            'protected' => false,
        ],
        'cv' => [
            'file' => 'cv.php',
            'urlPath' => ['/cv', '/cv/'],
            'path' => '/../app/views/cv.php',
            'route' => '/../views/layout.php',
            'title' => 'CV',
            'method' => ['GET'],
            'protected' => false,
        ],
        'cv/create' => [
            'file' => 'cv_create.php',
            'urlPath' => ['/cv/create', '/cv/creer'],
            'path' => '/../app/views/cv_create.php',
            'route' => '/../views/layout.php',
            'title' => 'Créer un CV',
            'method' => ['GET', 'POST'],
            'protected' => true,
        ],
        'cv/edit' => [
            'file' => 'cv_edit.php',
            'urlPath' => ['/cv/edit', '/cv/editer'],
            'path' => '/../app/views/cv_edit.php',
            'route' => '/../views/layout.php',
            'title' => 'Editer un CV',
            'method' => ['GET', 'POST'],
            'protected' => true,
        ],
        'cv/delete' => [
            'file' => 'cv_delete.php',
            'urlPath' => ['/cv/delete', '/cv/supprimer'],
            'path' => '/../app/views/cv_delete.php',
            'route' => '/../views/layout.php',
            'title' => 'Supprimer un CV',
            'method' => ['GET', 'POST'],
            'protected' => true,
        ],
        'dashboard' => [
            'file' => 'dashboard.php',
            'urlPath' => ['/dashboard'],
            'path' => '/../app/views/dashboard.php',
            'route' => '/../views/layout.php',
            'title' => 'Tableau de bord',
            'method' => ['GET'],
            'protected' => true,
        ],
        'profile' => [
            'file' => 'profile.php',
            'urlPath' => ['/profile'],
            'path' => '/../app/views/profile.php',
            'route' => '/../views/layout.php',
            'title' => 'Profil',
            'method' => ['GET'],
            'protected' => true,
        ],
        'settings' => [
            'file' => 'settings.php',
            'urlPath' => ['/settings', '/parametres'],
            'path' => '/../app/views/settings.php',
            'route' => '/../views/layout.php',
            'title' => 'Paramètres',
            'method' => ['GET', 'POST'],
            'protected' => true,
        ],
        'activity' => [
            'file' => 'activity.php',
            'urlPath' => ['/activity', '/activite'],
            'path' => '/../app/views/activity.php',
            'route' => '/../views/layout.php',
            'title' => 'Activité',
            'method' => ['GET'],
            'protected' => true,
        ],
        '404' => [
            'file' => '404.php',
            'urlPath' => ['/404'],
            'path' => '/../app/views/404.php',
            'route' => '/../views/layout.php',
            'title' => 'Page non trouvée',
            'method' => ['GET'],
            'protected' => false,
        ]
    ]
];